"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Programme = { id: string; country: string; level: string; program: string; university: string; fee: number; currency: string; duration: string; durationLabel: string };
type ChatMessage = { id: string; role: "user" | "assistant"; content: string; timestamp: number; programmes?: Programme[]; handoff?: string; quickReplies?: string[] };

const STARTERS = ["I want to study medicine. What options can I explore?", "Show all courses in Russia.", "Show undergraduate programmes in Malaysia.", "How can Strive help with my visa application?"];
const WHATSAPP = "263716730064";
const chatUrl = "/api/chat/stream";
const sessionKey = "strive-africa-floating-adviser-session";
const createSessionId = () => typeof crypto !== "undefined" && "randomUUID" in crypto ? crypto.randomUUID().replace(/-/g, "") : `strive-${Math.random().toString(36).slice(2)}`;
const createMessageId = (role: "user" | "assistant") => `${role}-${createSessionId()}`;
const timestampNow = () => Date.now();
const waUrl = (text: string) => `https://wa.me/${WHATSAPP}?text=${encodeURIComponent(`Hello Strive, ${text}`)}`;
const formatFee = (programme: Programme) => { const symbol = programme.currency === "USD" ? "$" : programme.currency === "EUR" ? "€" : ""; return `${symbol}${new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(programme.fee)} ${symbol ? "" : programme.currency}`.trim(); };
const parseEvent = (block: string) => { const event = block.split("\n").find(line => line.startsWith("event:"))?.slice(6).trim(); const raw = block.split("\n").find(line => line.startsWith("data:"))?.slice(5).trim(); if (!event || !raw) return undefined; try { return { event, data: JSON.parse(raw) as Record<string, unknown> }; } catch { return undefined; } };
const quickReplies = (question: string, hasProgrammes: boolean) => hasProgrammes ? ["Compare these programme options", "What should I prepare to apply?", "Help me choose a country"] : /visa/i.test(question) ? ["What should I prepare for my application?", "Find a programme for me", "How can Strive support my journey?"] : ["Find a programme for me", "Explore study destinations", "How does the application process work?"];

function ProgrammeOptions({ programmes }: { programmes: Programme[] }) {
  const [university, setUniversity] = useState("all"); const [level, setLevel] = useState("all"); const [feeBand, setFeeBand] = useState("any");
  const universities = useMemo(() => [...new Set(programmes.map(programme => programme.university))].sort(), [programmes]);
  const levels = useMemo(() => [...new Set(programmes.map(programme => programme.level))].sort(), [programmes]);
  const filtered = useMemo(() => programmes.filter(programme => (university === "all" || programme.university === university) && (level === "all" || programme.level === level) && (feeBand === "any" || feeBand === "2500" && programme.fee <= 2500 || feeBand === "5000" && programme.fee > 2500 && programme.fee <= 5000 || feeBand === "10000" && programme.fee > 5000 && programme.fee <= 10000 || feeBand === "over-10000" && programme.fee > 10000)), [feeBand, level, programmes, university]);
  const reset = () => { setUniversity("all"); setLevel("all"); setFeeBand("any"); };
  const active = university !== "all" || level !== "all" || feeBand !== "any";
  return <details className="striveChatOptions"><summary><span><b>Matching programme options</b><small>View {programmes.length} catalogue {programmes.length === 1 ? "option" : "options"}</small></span><i>⌄</i></summary><div className="striveChatOptionsBody"><div className="striveChatFilters"><label>University<select value={university} onChange={event => setUniversity(event.target.value)}><option value="all">All universities</option>{universities.map(option => <option key={option} value={option}>{option}</option>)}</select></label><label>Study level<select value={level} onChange={event => setLevel(event.target.value)}><option value="all">All levels</option>{levels.map(option => <option key={option} value={option}>{option}</option>)}</select></label><label>Listed fee amount<select value={feeBand} onChange={event => setFeeBand(event.target.value)}><option value="any">Any listed fee</option><option value="2500">Up to 2,500</option><option value="5000">2,501–5,000</option><option value="10000">5,001–10,000</option><option value="over-10000">Over 10,000</option></select></label></div><p className="striveChatFilterNote">Fee bands compare listed amounts; the currency on each card still applies.</p><div className="striveChatFilterSummary"><span>Showing {filtered.length} of {programmes.length} options</span>{active && <button type="button" onClick={reset}>Clear filters</button>}</div>{filtered.length ? filtered.map(programme => <article className="striveChatProgramme" key={programme.id}><div><span>{programme.country} · {programme.level}</span><h4>{programme.program}</h4><p>{programme.university}</p></div><b>{formatFee(programme)}</b>{(programme.durationLabel || programme.duration) && <small>Duration: {programme.durationLabel || programme.duration}</small>}<a href={waUrl(`I would like details about ${programme.program} at ${programme.university} in ${programme.country}. Level: ${programme.level}. Listed fee: ${programme.fee} ${programme.currency}.`)} target="_blank" rel="noreferrer">Request details from Strive ↗</a></article>) : <div className="striveChatEmpty"><b>No options match these filters.</b><button type="button" onClick={reset}>Reset filters</button></div>}</div></details>;
}

export default function StriveFloatingChat() {
  const [open, setOpen] = useState(false); const [messages, setMessages] = useState<ChatMessage[]>([]); const [input, setInput] = useState(""); const [streaming, setStreaming] = useState(false); const [sessionId, setSessionId] = useState(""); const scrollRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (event: KeyboardEvent) => event.key === "Escape" && setOpen(false); window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);
  useEffect(() => { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" }); }, [messages, streaming]);
  const clear = () => { if (streaming) return; const next = createSessionId(); window.localStorage.setItem(sessionKey, next); setSessionId(next); setMessages([]); };
  const submit = async (event?: FormEvent, requested = input) => {
    event?.preventDefault(); const question = requested.trim(); if (!question || streaming) return; setInput(""); const currentSession = sessionId || createSessionId(); if (!sessionId) { window.localStorage.setItem(sessionKey, currentSession); setSessionId(currentSession); }
    const assistantId = createMessageId("assistant"); const timestamp = timestampNow(); const history = [...messages.map(message => ({ role: message.role, content: message.content })), { role: "user" as const, content: question }].filter(message => message.content).slice(-10);
    setMessages(current => [...current, { id: createMessageId("user"), role: "user", content: question, timestamp }, { id: assistantId, role: "assistant", content: "", timestamp }]); setStreaming(true);
    try { const response = await fetch(chatUrl, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sessionId: currentSession, messages: history }) }); if (!response.ok || !response.body) throw new Error("The adviser is temporarily unavailable"); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = "";
      const apply = (block: string) => { const parsed = parseEvent(block); if (!parsed) return; if (parsed.event === "meta") setMessages(current => current.map(message => message.id === assistantId ? { ...message, programmes: Array.isArray(parsed.data.programmes) ? parsed.data.programmes as Programme[] : [], handoff: typeof parsed.data.handoff === "string" ? parsed.data.handoff : undefined } : message)); if (parsed.event === "token" && typeof parsed.data.token === "string") setMessages(current => current.map(message => message.id === assistantId ? { ...message, content: message.content + parsed.data.token } : message)); if (parsed.event === "done") setMessages(current => current.map(message => message.id === assistantId ? { ...message, quickReplies: quickReplies(question, Boolean(message.programmes?.length)) } : message)); if (parsed.event === "error") setMessages(current => current.map(message => message.id === assistantId ? { ...message, content: "I could not complete that answer just now. Please continue on WhatsApp and the Strive team will help.", handoff: waUrl(`My question: ${question}`), quickReplies: quickReplies(question, false) } : message)); };
      while (true) { const { done, value } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const blocks = buffer.split("\n\n"); buffer = blocks.pop() || ""; blocks.forEach(apply); }
    } catch { setMessages(current => current.map(message => message.id === assistantId ? { ...message, content: "I could not reach the adviser right now. Please continue on WhatsApp and the Strive team will help.", handoff: waUrl(`My question: ${question}`), quickReplies: quickReplies(question, false) } : message)); } finally { setStreaming(false); }
  };
  return <div className="striveChatFloat">{open && <section className="striveChatPanel" role="dialog" aria-label="Strive Africa programme adviser"><header><div><span>✦ STRIVE ADVISER</span><b>Your next step, made clearer.</b></div><div><button type="button" onClick={clear} disabled={streaming}>↻ <em>Clear</em></button><button type="button" onClick={() => setOpen(false)} aria-label="Close chat">×</button></div></header><div className="striveChatMessages" ref={scrollRef}>{messages.length === 0 ? <div className="striveChatWelcome"><span>✦ Grounded in Strive information</span><h2>Let’s find a route that fits.</h2><p>Ask about a course, country, fee, Strive service, eligibility, study guide or student journey.</p><div>{STARTERS.map(starter => <button type="button" key={starter} disabled={streaming} onClick={() => submit(undefined, starter)}>{starter} <i>↗</i></button>)}</div></div> : messages.map(message => <article key={message.id} className={`striveChatMessage ${message.role}`}><div className="striveChatBubble">{message.role === "assistant" && !message.content ? <span className="striveChatTyping" aria-label="Strive adviser is typing"><i/><i/><i/></span> : message.content}</div><small>{message.role === "assistant" ? "Strive adviser" : "You"} · {new Intl.DateTimeFormat("en", { hour: "numeric", minute: "2-digit" }).format(message.timestamp)}</small>{message.role === "assistant" && message.programmes?.length ? <ProgrammeOptions programmes={message.programmes} /> : null}{message.role === "assistant" && message.handoff && message.content ? <a className="striveChatHandoff" href={message.handoff} target="_blank" rel="noreferrer">Continue on WhatsApp ↗</a> : null}{message.role === "assistant" && message.quickReplies?.length ? <div className="striveChatReplies">{message.quickReplies.map(reply => <button type="button" key={reply} disabled={streaming} onClick={() => submit(undefined, reply)}>{reply}</button>)}</div> : null}</article>)}</div><form onSubmit={submit}><textarea value={input} onChange={event => setInput(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); submit(); } }} placeholder="Ask about a course, country, budget or service…" rows={1} disabled={streaming}/><button type="submit" disabled={!input.trim() || streaming} aria-label="Send message">↑</button></form><p className="striveChatLegal">Strive verifies fees, intakes, entry requirements and availability before every application.</p></section>}<button type="button" className="striveChatLauncher" onClick={() => setOpen(value => !value)} aria-expanded={open} aria-label="Ask Strive"><i>◌</i><span>Ask Strive</span>{open && <b>×</b>}</button></div>;
}
